//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenia
    {
        public long id_wypozyczenie { get; set; }
        public int id_czytelnik { get; set; }
        public int id_ksiazka { get; set; }
        public System.DateTime data_wypozyczenia { get; set; }
        public int id_pracownik_wypozyczenie { get; set; }
        public System.DateTime data_oddania { get; set; }
        public int id_pracownik_oddanie { get; set; }
    
        public virtual Czytelnicy Czytelnicy { get; set; }
        public virtual Ksiazki Ksiazki { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Pracownicy Pracownicy1 { get; set; }
    }
}
